---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 annotations:
  controller-gen.kubebuilder.io/version: v0.19.0
 name: tokenratelimitpolicies.kuadrant.io
spec:
 group: kuadrant.io
 names:
  kind: TokenRateLimitPolicy
  listKind: TokenRateLimitPolicyList
  plural: tokenratelimitpolicies
  singular: tokenratelimitpolicy
 scope: Namespaced
 versions:
 - additionalPrinterColumns:
  - description: TokenRateLimitPolicy Accepted
   jsonPath: .status.conditions[?(@.type=="Accepted")].status
   name: Accepted
   type: string
  - description: TokenRateLimitPolicy Enforced
   jsonPath: .status.conditions[?(@.type=="Enforced")].status
   name: Enforced
   type: string
  - jsonPath: .metadata.creationTimestamp
   name: Age
   type: date
  name: v1alpha1
  schema:
   openAPIV3Schema:
    description: TokenRateLimitPolicy is the Schema for the TokenRateLimitPolicies
     API
    properties:
     apiVersion:
      description: |-
       APIVersion defines the versioned schema of this representation of an object.
       Servers should convert recognized schemas to the latest internal value, and
       may reject unrecognized values.
       More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
      type: string
     kind:
      description: |-
       Kind is a string value representing the REST resource this object represents.
       Servers may infer this from the endpoint the client submits requests to.
       Cannot be updated.
       In CamelCase.
       More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
      type: string
     metadata:
      type: object
     spec:
      description: TokenRateLimitPolicySpec defines the desired state of TokenRateLimitPolicy
      properties:
       defaults:
        description: |-
         Default contains policy defaults. The policy is applied unless it is overridden at a lower level.
         It is mutually exclusive with Limits. Defaults mean to not include one or more implicit TokenLimit.
        properties:
         limits:
          additionalProperties:
           description: TokenLimit defines a token-based rate limit.
           properties:
            counters:
             description: |-
              Counters defines additional rate limit counters based on context qualifiers.
              Optional.
             items:
              description: ContextSelector defines one item from the well known attributes
               https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.
              minLength: 1
              type: string
             type: array
            rates:
             description: |-
              Rates holds the list of limit rates.
              At least one config must be provided.
             items:
              description: Rate defines the actual limit rate.
              properties:
               limit:
                description: Limit defines the max value allowed for a given
                 period of time
                type: integer
               window:
                description: |-
                 Window defines the time period for which the Limit specified applies
                 The value is a counter duration as defined in the definition of the CommonExpression Language (CEL).
                 Supported units are 'ns', 'us' (or 'µs'), 'ms', 's', 'm', 'h' (https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions) Allowed formats are '1h', '90m', '1d', '500ms', '45s', ...
                pattern: ^([0-9]{1,5}(h|m|s|ms)){1,4}$
                type: string
              required:
              - limit
              - window
              type: object
             minItems: 1
             type: array
            when:
             description: |-
              When holds the list of token-based conditions for the policy to be enforced.
              All attribute sets provided must evaluate to true for the limit to be enforced.
             items:
              description: WhenCondition defines condition for the token-based
               rate limit to be enforced
              properties:
               predicate:
                description: |-
                 Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
                 The predicate is evaluated at runtime and MUST evaluate to false or true.
                 +kubebuilder:validation:Required
                minLength: 1
                type: string
              required:
              - predicate
              type: object
             type: array
           required:
           - rates
           type: object
          description: |-
           Limits holds the token-based limits indexed by a unique name.
           At least one config must be provided.
          minProperties: 1
          type: object
         when:
          description: |-
           When holds the top-level conditions for the policy to be enforced.
           All attribute sets provided must evaluate to true for the limits to be enforced.
          items:
           description: WhenCondition defines condition for the token-based
            rate limit to be enforced
           properties:
            predicate:
             description: |-
              Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
              The predicate is evaluated at runtime and MUST evaluate to false or true.
              +kubebuilder:validation:Required
             minLength: 1
             type: string
           required:
           - predicate
           type: object
          type: array
        type: object
        x-kubernetes-validations:
        - message: The limits field must be set.
         rule: has(self.limits)
       limits:
        additionalProperties:
         description: TokenLimit defines a token-based rate limit.
         properties:
          counters:
           description: |-
            Counters defines additional rate limit counters based on context qualifiers.
            Optional.
           items:
            description: ContextSelector defines one item from the well known attributes
             https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.
            minLength: 1
            type: string
           type: array
          rates:
           description: |-
            Rates holds the list of limit rates.
            At least one config must be provided.
           items:
            description: Rate defines the actual limit rate.
            properties:
             limit:
              description: Limit defines the max value allowed for a given
               period of time
              type: integer
             window:
              description: |-
               Window defines the time period for which the Limit specified applies
               The value is a counter duration as defined in the definition of the CommonExpression Language (CEL).
               Supported units are 'ns', 'us' (or 'µs'), 'ms', 's', 'm', 'h' (https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions) Allowed formats are '1h', '90m', '1d', '500ms', '45s', ...
              pattern: ^([0-9]{1,5}(h|m|s|ms)){1,4}$
              type: string
            required:
            - limit
            - window
            type: object
           minItems: 1
           type: array
          when:
           description: |-
            When holds the list of token-based conditions for the policy to be enforced.
            All attribute sets provided must evaluate to true for the limit to be enforced.
           items:
            description: WhenCondition defines condition for the token-based
             rate limit to be enforced
            properties:
             predicate:
              description: |-
               Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
               The predicate is evaluated at runtime and MUST evaluate to false or true.
               +kubebuilder:validation:Required
              minLength: 1
              type: string
            required:
            - predicate
            type: object
           type: array
         required:
         - rates
         type: object
        description: |-
         Limits holds the token-based limits indexed by a unique name.
         At least one config must be provided.
        minProperties: 1
        type: object
       overrides:
        description: |-
         Overrides contains policy overrides. The policy is applied everywhere it is compatible.
         It is mutually exclusive with Limits and Defaults. Overrides mean to include one or more implicit TokenLimit.
        properties:
         limits:
          additionalProperties:
           description: TokenLimit defines a token-based rate limit.
           properties:
            counters:
             description: |-
              Counters defines additional rate limit counters based on context qualifiers.
              Optional.
             items:
              description: ContextSelector defines one item from the well known attributes
               https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.
              minLength: 1
              type: string
             type: array
            rates:
             description: |-
              Rates holds the list of limit rates.
              At least one config must be provided.
             items:
              description: Rate defines the actual limit rate.
              properties:
               limit:
                description: Limit defines the max value allowed for a given
                 period of time
                type: integer
               window:
                description: |-
                 Window defines the time period for which the Limit specified applies
                 The value is a counter duration as defined in the definition of the CommonExpression Language (CEL).
                 Supported units are 'ns', 'us' (or 'µs'), 'ms', 's', 'm', 'h' (https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions) Allowed formats are '1h', '90m', '1d', '500ms', '45s', ...
                pattern: ^([0-9]{1,5}(h|m|s|ms)){1,4}$
                type: string
              required:
              - limit
              - window
              type: object
             minItems: 1
             type: array
            when:
             description: |-
              When holds the list of token-based conditions for the policy to be enforced.
              All attribute sets provided must evaluate to true for the limit to be enforced.
             items:
              description: WhenCondition defines condition for the token-based
               rate limit to be enforced
              properties:
               predicate:
                description: |-
                 Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
                 The predicate is evaluated at runtime and MUST evaluate to false or true.
                 +kubebuilder:validation:Required
                minLength: 1
                type: string
              required:
              - predicate
              type: object
             type: array
           required:
           - rates
           type: object
          description: |-
           Limits holds the token-based limits indexed by a unique name.
           At least one config must be provided.
          minProperties: 1
          type: object
         when:
          description: |-
           When holds the top-level conditions for the policy to be enforced.
           All attribute sets provided must evaluate to true for the limits to be enforced.
          items:
           description: WhenCondition defines condition for the token-based
            rate limit to be enforced
           properties:
            predicate:
             description: |-
              Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
              The predicate is evaluated at runtime and MUST evaluate to false or true.
              +kubebuilder:validation:Required
             minLength: 1
             type: string
           required:
           - predicate
           type: object
          type: array
        type: object
        x-kubernetes-validations:
        - message: The limits field must be set.
         rule: has(self.limits)
       targetRef:
        description: TargetRef is the reference to the Gateway API resource
         to which the policy is applied.
        properties:
         group:
          description: Group is the group of the target resource.
          maxLength: 253
          pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
          type: string
         kind:
          description: Kind is kind of the target resource.
          maxLength: 63
          minLength: 1
          pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
          type: string
         name:
          description: Name is the name of the target resource.
          maxLength: 253
          minLength: 1
          type: string
         sectionName:
          description: |-
           SectionName is the name of a section within the target resource. When
           unspecified, this targetRef targets the entire resource. In the following
           resources, SectionName is interpreted as the following:

           * Gateway: Listener name
           * HTTPRoute: HTTPRouteRule name
           * Service: Port name

           If a SectionName is specified, but does not exist on the targeted object,
           the Policy must fail to attach, and the policy implementation should record
           a `ResolvedRefs` or similar Condition in the Policy's status.
          maxLength: 253
          minLength: 1
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
          type: string
        required:
        - group
        - kind
        - name
        type: object
        x-kubernetes-validations:
        - message: Invalid targetRef.group. The only supported value is 'gateway.networking.k8s.io'
         rule: self.group == 'gateway.networking.k8s.io'
        - message: Invalid targetRef.kind. The only supported values are 'HTTPRoute'
          and 'Gateway'
         rule: self.kind == 'HTTPRoute' || self.kind == 'Gateway'
       when:
        description: |-
         When holds the top-level conditions for the policy to be enforced.
         All attribute sets provided must evaluate to true for the limits to be enforced.
        items:
         description: WhenCondition defines condition for the token-based
          rate limit to be enforced
         properties:
          predicate:
           description: |-
            Predicate is a CEL expression that returns a boolean result, if set to true the limit is considered.
            The predicate is evaluated at runtime and MUST evaluate to false or true.
            +kubebuilder:validation:Required
           minLength: 1
           type: string
         required:
         - predicate
         type: object
        type: array
      required:
      - targetRef
      type: object
      x-kubernetes-validations:
      - message: Implicit defaults and explicit defaults are mutually exclusive
       rule: '!(has(self.defaults) && !has(self.defaults.limits))'
      - message: Implicit overrides and explicit overrides are mutually exclusive
       rule: '!(has(self.overrides) && !has(self.overrides.limits))'
      - message: Defaults and overrides are mutually exclusive
       rule: '!(has(self.defaults) && has(self.overrides))'
      - message: Defaults and limits are mutually exclusive
       rule: '!(has(self.defaults) && has(self.limits))'
      - message: Overrides and limits are mutually exclusive
       rule: '!(has(self.overrides) && has(self.limits))'
      - message: At least one of limits, defaults or overrides must be set.
       rule: has(self.limits) || has(self.defaults) || has(self.overrides)
     status:
      description: TokenRateLimitPolicyStatus defines the observed state of TokenRateLimitPolicy
      properties:
       conditions:
        description: |-
         Represents the observations of a TokenRateLimitPolicy's current state.
         Known .status.conditions.type are: "Accepted", "Enforced"
        items:
         description: Condition contains details for one aspect of the current
          state of this API Resource.
         properties:
          lastTransitionTime:
           description: |-
            lastTransitionTime is the last time the condition transitioned from one status to another.
            This should be when the underlying condition changed. If that is not known, then using the time when the API field changed is acceptable.
           format: date-time
           type: string
          message:
           description: |-
            message is a human readable message indicating details about the transition.
            This may be an empty string.
           maxLength: 32768
           type: string
          observedGeneration:
           description: |-
            observedGeneration represents the .metadata.generation that the condition was set based upon.
            For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
            with respect to the current state of the instance.
           format: int64
           minimum: 0
           type: integer
          reason:
           description: |-
            reason contains a programmatic identifier indicating the reason for the condition's last transition.
            Producers of specific condition types may define expected values and meanings for this field,
            and whether the values are considered a guaranteed API.
            The value should be a CamelCase string.
            This field may not be empty.
           maxLength: 1024
           minLength: 1
           pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
           type: string
          status:
           description: status of the condition, one of True, False, Unknown.
           enum:
           - "True"
           - "False"
           - Unknown
           type: string
          type:
           description: type of condition in CamelCase or in foo.example.com/CamelCase.
           maxLength: 316
           pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
           type: string
         required:
         - lastTransitionTime
         - message
         - reason
         - status
         - type
         type: object
        type: array
        x-kubernetes-list-map-keys:
        - type
        x-kubernetes-list-type: map
       observedGeneration:
        description: ObservedGeneration reflects the generation of the most
         recently observed spec.
        format: int64
        type: integer
      type: object
    type: object
  served: true
  storage: true
  subresources:
   status: {}
