{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: kuadrant-operator
 labels:
  app.kubernetes.io/name: kuadrant-operator
  app.kubernetes.io/managed-by: helm
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: kuadrant-operator
subjects:
 - kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end }}
