{{- if .Values.pullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
 name: {{ .Values.pullSecret.name }}
 namespace: {{ .Values.namespace }}
 labels:
  app.kubernetes.io/name: kuadrant-operator
  app.kubernetes.io/managed-by: helm
type: kubernetes.io/dockerconfigjson
stringData:
 .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | quote }}
{{- end }}
