apiVersion: v2
name: cert-manager-operator
description: Red Hat cert-manager Operator for vanilla Kubernetes (without OLM)
type: application
version: 1.0.2
appVersion: "1.15.2"
keywords:
  - cert-manager
  - certificates
  - tls
  - operator
  - openshift
maintainers:
  - name: Red Hat
