apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: cert-manager-operator
  name: cert-manager-operator-controller-manager
  namespace: {{ .Values.operatorNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-manager-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      labels:
        name: cert-manager-operator
      namespace: {{ .Values.operatorNamespace }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - start
            - --v=$(OPERATOR_LOG_LEVEL)
            - --trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)
            - --cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)
            - --unsupported-addon-features=$(UNSUPPORTED_ADDON_FEATURES)
          command:
            - /usr/bin/cert-manager-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:76fe0671c410cb063225ecfa51c30f86634518a48757ee69bd2662f0643b5f40
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:76fe0671c410cb063225ecfa51c30f86634518a48757ee69bd2662f0643b5f40
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:76fe0671c410cb063225ecfa51c30f86634518a48757ee69bd2662f0643b5f40
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:80d9e21cee7578e80ef80628436c5ce0d7af3118d161a196c31b8b1825e04dc7
            - name: RELATED_IMAGE_CERT_MANAGER_ISTIOCSR
              value: registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:9573d74bd2b926ec94af76f813e6358f14c5b2f4e0eedab7c1ff1070b7279a5c
            - name: OPERAND_IMAGE_VERSION
              value: 1.15.5
            - name: ISTIOCSR_OPERAND_IMAGE_VERSION
              value: 0.14.0
            - name: OPERATOR_IMAGE_VERSION
              value: 1.15.2
            - name: OPERATOR_LOG_LEVEL
              value: "2"
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
            - name: UNSUPPORTED_ADDON_FEATURES
          image: registry.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:7c91cda4ad5b62f1f1bad8466fa94f54d0c5ab82296f2e8e22bf87d996f6c40e
          imagePullPolicy: IfNotPresent
          name: cert-manager-operator
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cert-manager-operator-controller-manager
      terminationGracePeriodSeconds: 10
