{{- if .Values.pullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.operatorNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.operandNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerConfigJson | b64enc }}
{{- end }}
