{{- $serviceAccounts := list "cert-manager" "cert-manager-cainjector" "cert-manager-webhook" }}
{{- range $serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.operandNamespace }}
imagePullSecrets:
  - name: {{ $.Values.pullSecret.name }}
{{- end }}
